### ISSUE TITLE
Templates Erroring Out

### ISSUE THREAD

**Issue by bannsec** [d0c-s4vage/pfp#22] opened 2015-09-28 17:49 UTC
I've attempted to run your application with both your demo template as well as some standard ones that I downloaded and use successfully in 010editor (http://www.sweetscape.com/010editor/templates/files/PNG12Template.bt). Error of "PrematureEOF".

Something seems very wrong with your product...

**Comment by d0c-s4vage** [comment] 2015-09-29 01:12
Could you please provide the error messages, along with which OS and version of python you are using? I really don't have much to go off of from your description.

Thanks.

**Comment by d0c-s4vage** [comment] 2016-09-14 17:30
Was able to duplicate this:

```
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    template=template,
  File "/home/james/__ws__/dev/pfp/pfp/__init__.py", line 85, in parse
    keep_successful = keep_successful
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 672, in parse
    res = self._run(keep_successful)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 865, in _run
    traceback
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 844, in _run
    res = self._handle_node(self._ast, None, None, self._stream)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 937, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 960, in _handle_file_ast
    self._handle_node(child, scope, ctxt, stream)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 937, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 2096, in _handle_while
    self._handle_node(node.stmt, scope, ctxt, stream)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 937, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 1924, in _handle_compound
    self._handle_node(child, scope, ctxt, stream)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 937, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 1151, in _handle_decl
    field._pfp__init(stream)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 81, in _pfp__init
    stream=stream
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 937, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 1436, in _handle_struct_decls
    self._handle_node(decl, scope, ctxt, stream)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 937, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 1124, in _handle_decl
    bitfield_left_right=bitfield_left_right
  File "/home/james/__ws__/dev/pfp/pfp/fields.py", line 985, in __init__
    super(NumberBase, self).__init__(stream, metadata_processor=metadata_processor)
  File "/home/james/__ws__/dev/pfp/pfp/fields.py", line 231, in __init__
    self._pfp__parse(stream, save_offset=True)
  File "/home/james/__ws__/dev/pfp/pfp/fields.py", line 1023, in _pfp__parse
    raise errors.PrematureEOF()
pfp.errors.PfpError: 
Exception at string:19
```

**Comment by d0c-s4vage** [comment] 2016-09-14 17:33
This isn't a problem in the pfp source, but a problem in my example code at https://d0cs4vage.blogspot.com/2015/08/pfp-python-interpreter-for-010-templates.html.

The endianness is wrong. Explicitly setting it to BigEndian() fixes this problem:

``` c
    BigEndian();

    typedef struct {
        // null-terminated
        string label;

        char comment[length - sizeof(label)];
    } TEXT;

    typedef struct {
        uint length<watch=data, update=WatchLength>;
        char cname[4];

        union {
            char raw[length];

            if(cname == "tEXt") {
                TEXT tEXt;
            }
        } data;
        Int3();
        uint crc<watch=cname;data, update=WatchCrc32>;
    } CHUNK;

    uint64 magic;

    while(!FEof()) {
        CHUNK chunks;
    }
```

**Comment by d0c-s4vage** [comment] 2016-09-14 17:34
blog has been updated, closing with invalid label since it's not a bug in the pfp source code.

**Closed as completed by d0c-s4vage** 2016-09-14 17:34 UTC
Labels: bug, invalid
