### ISSUE TITLE
FindFirst  fail

### ISSUE THREAD

**Issue by 0x140ce** [d0c-s4vage/pfp#78] opened 2019-09-24 08:23 UTC
![image](https://user-images.githubusercontent.com/33895336/65494028-a692e580-dee6-11e9-9567-78be391e4b8d.png)
![image](https://user-images.githubusercontent.com/33895336/65494501-8e6f9600-dee7-11e9-8f87-96f2faffe2eb.png)

I use the same jpg.BT in 010edit and pfp to parse the follow jpg file ,but pfp failed to call function FindFirst()

[jpg.bt.txt](https://github.com/d0c-s4vage/pfp/files/3646040/jpg.bt.txt)

![1](https://user-images.githubusercontent.com/33895336/65494244-02f60500-dee7-11e9-959d-573778f52abc.jpg)

**Comment by d0c-s4vage** [comment] 2019-09-25 20:45
Thanks for reporting the error and including the template script and the jpg!

Could you also say which version of pfp you're using and on which platform and architecture? It looks like Windows 7

**Comment by 0x140ce** [comment] 2019-09-26 02:40
I clone from github and use cmd "python setup.py install"  yesterday.
The system is windows 7 64bit.
PS:I use this cpp.exe(https://github.com/d0c-s4vage/py010parser/blob/master/utils/cpp.exe)

**Comment by d0c-s4vage** [comment] 2019-09-29 14:53
![image](https://user-images.githubusercontent.com/5090146/65833838-83bb5500-e289-11e9-83e9-775e64618a65.png)
reproduced

**Comment by d0c-s4vage** [comment] 2019-09-30 03:17
Looks like pfp doesn't treat enum types correctly:

```c
typedef enum <WORD> tagID
{
 M_SOF0 = 0xFFC0,
 M_SOF1,
 M_SOF2,
 M_SOF3,
 M_DHT,
 M_SOF5,
 M_SOF6,
 M_SOF7,
 M_JPG,
 M_SOF9,
 M_SOF10,
 M_SOF11,
 M_DAC = 0xffcc,
 M_SOF13,
 M_SOF14,
 M_SOF15,
 M_RST0 = 0xffd0,
 M_RST1, M_RST2, M_RST3, M_RST4, M_RST5, M_RST6, M_RST7,
 M_SOI = 0xFFD8,
 M_EOI,
 // ...
}
```
in pfp debugger, `M_EOI` is interpreted as an Int instead of a USHORT, which is what `WORD` should be:
![image](https://user-images.githubusercontent.com/5090146/65847310-ddf1ff80-e2f5-11e9-96e6-dccd7f031f2b.png)

I still need to trace this down a bit, there still might be something else going on

**Comment by d0c-s4vage** [comment] 2019-09-30 03:29
Aha, pfp doesn't handle typed enums with starting values correctly. Fixing this problem in another specific ticket

**Comment by d0c-s4vage** [comment] 2019-09-30 04:06
With #80 fixed, the output is now:
```
 lptp [ pfp ]: python -c "import pfp ; pfp.parse(data_file='tests/data/balloons.jpg', template_file='tests/templates/jpg.bt')"
Start of Image Marker
Start of Scan Marker
623
16012
End of File Image
```
This seems correct, closing the issue

**Closed as completed by d0c-s4vage** 2019-09-30 04:06 UTC
