### ISSUE TITLE
PrematureEOF

### ISSUE THREAD

**Issue by c3c** [d0c-s4vage/pfp#20] opened 2015-09-24 20:15 UTC
Hello,

I'm getting a PrematureEOF error while attempting to run the demo script as found at http://d0cs4vage.blogspot.nl/2015/08/pfp-python-interpreter-for-010-templates.html with a few random PNGs:

```
$ python lal.py 
Traceback (most recent call last):
  File "lal.py", line 41, in <module>
    template=template,
  File "/home/pen/tools/png/pfp/__init__.py", line 64, in parse
    dom = interp.parse(data, template, predefines=predefines, orig_filename=orig_filename, keep_successful=keep_successful)
  File "/home/pen/tools/png/pfp/interp.py", line 670, in parse
    res = self._run(keep_successful)
  File "/home/pen/tools/png/pfp/interp.py", line 874, in _run
    traceback
  File "/home/pen/tools/png/pfp/interp.py", line 853, in _run
    res = self._handle_node(self._ast, None, None, self._stream)
  File "/home/pen/tools/png/pfp/interp.py", line 946, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/home/pen/tools/png/pfp/interp.py", line 969, in _handle_file_ast
    self._handle_node(child, scope, ctxt, stream)
  File "/home/pen/tools/png/pfp/interp.py", line 946, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/home/pen/tools/png/pfp/interp.py", line 2087, in _handle_while
    self._handle_node(node.stmt, scope, ctxt, stream)
  File "/home/pen/tools/png/pfp/interp.py", line 946, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/home/pen/tools/png/pfp/interp.py", line 1919, in _handle_compound
    self._handle_node(child, scope, ctxt, stream)
  File "/home/pen/tools/png/pfp/interp.py", line 946, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/home/pen/tools/png/pfp/interp.py", line 1154, in _handle_decl
    field._pfp__init(stream)
  File "/home/pen/tools/png/pfp/interp.py", line 80, in _pfp__init
    stream=stream
  File "/home/pen/tools/png/pfp/interp.py", line 946, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/home/pen/tools/png/pfp/interp.py", line 1431, in _handle_struct_decls
    self._handle_node(decl, scope, ctxt, stream)
  File "/home/pen/tools/png/pfp/interp.py", line 946, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "/home/pen/tools/png/pfp/interp.py", line 1127, in _handle_decl
    bitfield_left_right=self._bitfield_left_right
  File "/home/pen/tools/png/pfp/fields.py", line 968, in __init__
    super(NumberBase, self).__init__(stream, metadata_processor=metadata_processor)
  File "/home/pen/tools/png/pfp/fields.py", line 219, in __init__
    self._pfp__parse(stream, save_offset=True)
  File "/home/pen/tools/png/pfp/fields.py", line 1006, in _pfp__parse
    raise errors.PrematureEOF()
pfp.errors.PfpError: 
Exception at string:20
```

Any idea what could cause this error?

**Comment by bannsec** [comment] 2015-09-28 17:44
I get the same error when attempting to run the demo lines that you put on your documentation...

**Comment by d0c-s4vage** [comment] 2015-09-28 21:19
Hrmm, thanks for reporting this. I'll try to get to it in the next couple of days.

**Comment by d0c-s4vage** [comment] 2016-09-14 17:37
This was a bug in my example code. I wasn't explicitly setting the endianness in the 010 template. The blog has been updated (added `BigEndian()` as the first statement in the example template). See also https://github.com/d0c-s4vage/pfp/issues/22

**Comment by d0c-s4vage** [comment] 2016-09-14 17:38
Closing with invalid label since it's not a bug in the pfp source code, but a bug in my example code on the blog.

**Closed as completed by d0c-s4vage** 2016-09-14 17:38 UTC
Labels: bug, invalid
